In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


df=pd.read_csv('superstore.csv')

df

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,13540-132521-3244,132521,13540,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,Appliances,Office Supplies,0.0,2017-09-23,23,9,Saturday,2017,2,Consumer,Washington,26157,93419
9989,17560-143105-12682,143105,17560,Hewlett Packard 610 Color Digital Copier / Pri...,Copiers,Technology,0.2,2015-12-10,10,12,Thursday,2015,2,Home Office,New York,194684,622988
9990,12250-149811-16023,149811,12250,"GBC Standard Recycled Report Covers, Clear Pla...",Binders,Office Supplies,0.0,2015-01-04,4,1,Sunday,2015,3,Corporate,Minnesota,12089,25185
9991,10300-166800-21126,166800,10300,Hoover Commercial Soft Guard Upright Vacuum An...,Appliances,Office Supplies,0.0,2015-11-19,19,11,Thursday,2015,4,Corporate,Nevada,6535,24204
9992,10720-136322-29264,136322,10720,GBC Personal VeloBind Strips,Binders,Office Supplies,0.7,2016-10-21,21,10,Friday,2016,8,Home Office,Florida,-16420,22391

In [2]:
print("Dimenciones del dataset: ",df.shape)

Dimenciones del dataset:  (9993, 17)

In [3]:
#Visualizar el nmbre de todas las columnas

df.columns.tolist()

['Transaction ID',
 'Order ID',
 'Customer ID',
 'Product Name',
 'Sub-Category',
 'Category',
 'Discount',
 'Order Date',
 'Order Day',
 'Order Month',
 'Order Weekday',
 'Order Year',
 'Quantity',
 'Segment',
 'State',
 'Profit CLP',
 'Sales CLP']

In [5]:
#Imprimir iforacion sobre el dataframe, incluido el tipo de indice

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 9993 entries, 0 to 9992
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  9993 non-null   str
 1   Order ID        9993 non-null   int64
 2   Customer ID     9993 non-null   int64
 3   Product Name    9993 non-null   str
 4   Sub-Category    9993 non-null   str
 5   Category        9993 non-null   str
 6   Discount        9993 non-null   float64
 7   Order Date      9993 non-null   str
 8   Order Day       9993 non-null   int64
 9   Order Month     9993 non-null   int64
 10  Order Weekday   9993 non-null   str
 11  Order Year      9993 non-null   int64
 12  Quantity        9993 non-null   int64
 13  Segment         9993 non-null   str
 14  State           9993 non-null   str
 15  Profit CLP      9993 non-null   int64
 16  Sales CLP       9993 non-null   int64
dtypes: float64(1), int64(8), str(8)
memory usage: 1.3 MB
None

In [ ]:
#contabilizar nulls si aplica
pd.set_option('display.max_rows',None)
df.isna().sum()

Transaction ID    0
Order ID          0
Customer ID       0
Product Name      0
Sub-Category      0
Category          0
Discount          0
Order Date        0
Order Day         0
Order Month       0
Order Weekday     0
Order Year        0
Quantity          0
Segment           0
State             0
Profit CLP        0
Sales CLP         0
dtype: int64

In [ ]:
#imprmir las primera x filas

df.head(4)

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826

In [10]:
#ver ultimas filas

df.tail(3)

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
9990,12250-149811-16023,149811,12250,"GBC Standard Recycled Report Covers, Clear Pla...",Binders,Office Supplies,0.0,2015-01-04,4,1,Sunday,2015,3,Corporate,Minnesota,12089,25185
9991,10300-166800-21126,166800,10300,Hoover Commercial Soft Guard Upright Vacuum An...,Appliances,Office Supplies,0.0,2015-11-19,19,11,Thursday,2015,4,Corporate,Nevada,6535,24204
9992,10720-136322-29264,136322,10720,GBC Personal VeloBind Strips,Binders,Office Supplies,0.7,2016-10-21,21,10,Friday,2016,8,Home Office,Florida,-16420,22391

In [12]:
#seleccionar la columna "product name"
#string cuando es solo una variable
#para dos o mas variables, debe ser una lista


product_name=df["Product Name"]
product_name.head(10)

0                                             Xerox 22
1                                           Xerox 1925
2    Logitech 910-002974 M325 Wireless Mouse for We...
3               Contico 72"H Heavy-Duty Storage System
4                        PowerGen Dual USB Car Charger
5             Hewlett Packard 310 Color Digital Copier
6    Acme Office Executive Series Stainless Steel T...
7                               GBC Instant Report Kit
8              DAX Black Cherry Wood-Tone Poster Frame
9                           GBC Durable Plastic Covers
Name: Product Name, dtype: str